#!/bin/bash

#check where this script is running from
echo INFO: Pre-commit hook running from $PWD
git version

# Stash any changes to the working tree that are not going to be committed
git stash -q --keep-index

#check that the EDAM source file is in the right format (RDF/XML)
grep -c 'owl:Class' EDAM_dev.owl
owlclassfound=$?

# Unstash changes to the working tree that we had stashed
git stash pop -q

exit $owlclassfound
