#!/bin/bash
#check where this script is running from
echo Pre-commit hook running from $PWD
#check that the EDAM source file is in the right format (RDF/XML)
grep -c 'owl:Class' EDAM_dev.owl
owlclassfound=$?
exit $owlclassfound
