#!/bin/bash

#check where this script is running from
echo INFO: Pre-commit hook running from $PWD
git version

#check that the EDAM source file is in the right format (RDF/XML)
nowlclass=$(grep -c 'owl:Class' EDAM_dev.owl)
owlclassfound=$?
# $? returns operation successful (0) or unsuccessful (1)

#check if owl:Class was found in the source file and print # of  occurrences
if $owlclassfound; then
  echo ERROR: no owl:Class found.
else
  echo INFO: owl:Class found $nowlclass times.
fi
exit $owlclassfound
