#!/bin/bash

# Check where this script is running from
echo INFO: Pre-commit hook running from $PWD

# Check which Git is running
echo INFO about running Git:
which git
git --version
where git

# Validate EDAM source file
echo INFO: Validating EDAM source file. Exit code:
sh validate.sh
valid=$?
# valid>0 is success
exit $valid
