name: EDAMCI

on: [workflow_dispatch, workflow_call]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        git clone https://github.com/edamontology/edam-validation.git
        cd edam-validation/edamci/
        pip install -r requirements.txt

    - name: run 
      run: |
        cd edam-validation/edamci/
        EDAM_PATH=../../EDAM_dev.owl python3 edamci.py -e -E  # run only essential and error tests
     
    # - name: Print output
    #   if: always()
    #   run: |
    #     cat output_edamci.tsv 

    - name: Archive tests output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: output_edamci
        path: edam-validation/edamci/output_edamci.tsv